UEOChoixBundle_etudiant:
        resource: "@UEOChoixBundle/Resources/config/routing/home.yml"
        prefix:   /home
UEOChoixBundle_etudiant:
        resource: "@UEOChoixBundle/Resources/config/routing/etudiant.yml"
        prefix:   /etudiant
UEOChoixBundle_specialite:
        resource: "@UEOChoixBundle/Resources/config/routing/specialite.yml"
        prefix:   /specialite
UEOChoixBundle_module:
        resource: "@UEOChoixBundle/Resources/config/routing/module.yml"
        prefix:   /module
UEOChoixBundle_parcours:
        resource: "@UEOChoixBundle/Resources/config/routing/parcours.yml"
        prefix:   /parcours
UEOChoixBundle_moduleparcours:
        resource: "@UEOChoixBundle/Resources/config/routing/moduleparcours.yml"
        prefix:   /maquette