UEO\ChoixBundle\Entity\Choix:
    type: entity
    table: null
    repositoryClass: UEO\ChoixBundle\Entity\ChoixRepository
    id:
        etudiant:
            associationKey: true
        module:
            associationKey: true
    fields:
        dateChoix:
            type: datetime
    oneToOne:
        etudiant:
            targetEntity: Etudiant
        module:
            targetEntity: Module
    lifecycleCallbacks: {  }
