module:
    pattern:  /
    defaults: { _controller: "UEOChoixBundle:Module:index" }

module_show:
    pattern:  /{id}/show
    defaults: { _controller: "UEOChoixBundle:Module:show" }

module_new:
    pattern:  /new
    defaults: { _controller: "UEOChoixBundle:Module:new" }

module_create:
    pattern:  /create
    defaults: { _controller: "UEOChoixBundle:Module:create" }
    requirements: { _method: post }

module_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "UEOChoixBundle:Module:edit" }

module_update:
    pattern:  /{id}/update
    defaults: { _controller: "UEOChoixBundle:Module:update" }
    requirements: { _method: post|put }

module_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "UEOChoixBundle:Module:delete" }
    requirements: { _method: post|delete }

module_supprimer:
    pattern:  /{id}/supprimer
    defaults: { _controller: "UEOChoixBundle:Module:supprimer" }
